import { UserProfile, ActivityItem } from '@/types/user';
import { Project } from '@/types/project';
import { Task } from '@/types/task';
import { ProductivitySummary } from '@/types/api';

export const MOCK_USER: UserProfile = {
  id: 'usr_98a72f01',
  name: 'Alex Vance',
  username: 'alexvance',
  email: 'alex.vance@acme-labs.io',
  role: 'lead_developer',
  roleDisplay: 'Staff Full-Stack Architect',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
  team: 'Core Platform & DX',
  department: 'Product Engineering',
  status: 'in_flow',
  bio: 'Building hyper-scalable distributed UI architecture, high-throughput microservices, and design systems.',
  joinedAt: '2023-01-15T08:00:00Z',
  stats: {
    tasksCompleted: 42,
    openPRs: 5,
    streakDays: 14,
    focusHoursWeekly: 34.5,
    codeReviewsGiven: 18,
    velocityScore: 94,
    completionRate: 88,
  },
};

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj_cloud_nexus',
    key: 'NEX',
    title: 'Nexus Cloud Control Plane',
    description: 'Next-generation distributed cloud orchestrator and multi-region Kubernetes gateway UI.',
    category: 'infra',
    status: 'in_progress',
    health: 'on_track',
    progress: 76,
    dueDate: '2026-10-25T18:00:00Z',
    createdAt: '2026-07-01T10:00:00Z',
    updatedAt: '2026-09-10T14:32:00Z',
    totalTasks: 24,
    completedTasks: 18,
    openIssues: 3,
    tags: ['Kubernetes', 'Go', 'Next.js 14', 'gRPC'],
    colorAccent: 'from-blue-500 to-indigo-600',
    repositoryUrl: 'https://github.com/acme/nexus-control-plane',
    members: [
      {
        id: 'mem_1',
        name: 'Alex Vance',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
        role: 'Tech Lead',
      },
      {
        id: 'mem_2',
        name: 'Marcus Chen',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
        role: 'Backend Engineer',
      },
      {
        id: 'mem_3',
        name: 'Elena Rostova',
        avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
        role: 'DevOps Architect',
      },
    ],
    stats: {
      commitsCount: 142,
      pullRequestsCount: 12,
      deploymentStatus: 'healthy',
    },
  },
  {
    id: 'proj_synth_ai',
    key: 'SYN',
    title: 'Synthetic Data & ML Pipeline',
    description: 'Automated privacy-preserving synthetic data generation engine with differential privacy.',
    category: 'ai',
    status: 'in_progress',
    health: 'at_risk',
    progress: 54,
    dueDate: '2026-11-15T18:00:00Z',
    createdAt: '2026-06-15T09:00:00Z',
    updatedAt: '2026-09-11T11:20:00Z',
    totalTasks: 18,
    completedTasks: 10,
    openIssues: 5,
    tags: ['Python', 'PyTorch', 'VectorDB', 'FastAPI'],
    colorAccent: 'from-violet-500 to-purple-600',
    repositoryUrl: 'https://github.com/acme/synthetic-data-engine',
    members: [
      {
        id: 'mem_1',
        name: 'Alex Vance',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
        role: 'Full Stack',
      },
      {
        id: 'mem_4',
        name: 'Sarah Connor',
        avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
        role: 'ML Researcher',
      },
    ],
    stats: {
      commitsCount: 98,
      pullRequestsCount: 7,
      deploymentStatus: 'warning',
    },
  },
  {
    id: 'proj_pulse_design',
    key: 'PUL',
    title: 'Pulse Design System v3',
    description: 'Component library overhaul with tokenized micro-interactions, WCAG AAA accessibility, and dark mode.',
    category: 'frontend',
    status: 'active',
    health: 'on_track',
    progress: 92,
    dueDate: '2026-09-30T18:00:00Z',
    createdAt: '2026-05-10T11:00:00Z',
    updatedAt: '2026-09-11T16:45:00Z',
    totalTasks: 32,
    completedTasks: 29,
    openIssues: 1,
    tags: ['Tailwind CSS', 'Framer Motion', 'Radix UI', 'Storybook'],
    colorAccent: 'from-emerald-400 to-teal-600',
    repositoryUrl: 'https://github.com/acme/pulse-ui-tokens',
    members: [
      {
        id: 'mem_1',
        name: 'Alex Vance',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
        role: 'Author',
      },
      {
        id: 'mem_5',
        name: 'Liam Neeson',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
        role: 'UI Designer',
      },
    ],
    stats: {
      commitsCount: 230,
      pullRequestsCount: 3,
      deploymentStatus: 'healthy',
    },
  },
  {
    id: 'proj_apex_edge',
    key: 'APX',
    title: 'Apex Edge Cache API Gateway',
    description: 'Ultra-low latency global caching worker layer with Cloudflare Workers and WebAssembly compute.',
    category: 'backend',
    status: 'planning',
    health: 'on_track',
    progress: 35,
    dueDate: '2026-12-20T18:00:00Z',
    createdAt: '2026-08-01T14:00:00Z',
    updatedAt: '2026-09-08T09:15:00Z',
    totalTasks: 14,
    completedTasks: 5,
    openIssues: 2,
    tags: ['Rust', 'Wasm', 'Workers', 'Redis'],
    colorAccent: 'from-amber-400 to-orange-600',
    repositoryUrl: 'https://github.com/acme/apex-edge-gateway',
    members: [
      {
        id: 'mem_2',
        name: 'Marcus Chen',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
        role: 'Systems Architect',
      },
      {
        id: 'mem_1',
        name: 'Alex Vance',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
        role: 'Integration Lead',
      },
    ],
    stats: {
      commitsCount: 45,
      pullRequestsCount: 4,
      deploymentStatus: 'healthy',
    },
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 'task_001',
    key: 'NEX-104',
    title: 'Implement dynamic 3D topology telemetry visualization',
    description: 'Use React Three Fiber to display low-poly cluster nodes and connection links with live throughput pulses.',
    status: 'in_progress',
    priority: 'high',
    projectId: 'proj_cloud_nexus',
    projectName: 'Nexus Cloud Control Plane',
    assignee: MOCK_PROJECTS[0].members[0],
    dueDate: '2026-09-18T18:00:00Z',
    estimatedHours: 12,
    loggedHours: 8,
    tags: ['3D', 'Three.js', 'Frontend'],
    commentsCount: 5,
    createdAt: '2026-09-05T10:00:00Z',
    updatedAt: '2026-09-11T14:20:00Z',
  },
  {
    id: 'task_002',
    key: 'NEX-109',
    title: 'Optimize gRPC streaming channel heartbeat timeout',
    description: 'Reduce connection drop rate across multi-cloud regions by tuning Envoy keepalive parameters.',
    status: 'todo',
    priority: 'urgent',
    projectId: 'proj_cloud_nexus',
    projectName: 'Nexus Cloud Control Plane',
    assignee: MOCK_PROJECTS[0].members[1],
    dueDate: '2026-09-14T12:00:00Z',
    estimatedHours: 6,
    loggedHours: 1,
    tags: ['gRPC', 'Networking', 'Go'],
    commentsCount: 2,
    createdAt: '2026-09-08T11:30:00Z',
    updatedAt: '2026-09-09T09:00:00Z',
  },
  {
    id: 'task_003',
    key: 'SYN-44',
    title: 'Benchmark diffusion noise scheduling in synthetic data sampler',
    description: 'Evaluate inference speedup when quantizing unet weights to FP8 for table synthesis.',
    status: 'in_review',
    priority: 'high',
    projectId: 'proj_synth_ai',
    projectName: 'Synthetic Data & ML Pipeline',
    assignee: MOCK_PROJECTS[1].members[1],
    dueDate: '2026-09-15T17:00:00Z',
    estimatedHours: 16,
    loggedHours: 15,
    tags: ['PyTorch', 'Quantization', 'AI'],
    commentsCount: 8,
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-11T12:00:00Z',
  },
  {
    id: 'task_004',
    key: 'PUL-88',
    title: 'Publish accessible dark mode color scales to npm registry',
    description: 'Ensure all contrast ratios satisfy APCA bronze level and WCAG 2.2 AAA standards.',
    status: 'done',
    priority: 'medium',
    projectId: 'proj_pulse_design',
    projectName: 'Pulse Design System v3',
    assignee: MOCK_PROJECTS[2].members[0],
    dueDate: '2026-09-10T18:00:00Z',
    estimatedHours: 8,
    loggedHours: 7.5,
    tags: ['Design System', 'Accessibility', 'CSS'],
    commentsCount: 3,
    createdAt: '2026-09-02T13:10:00Z',
    updatedAt: '2026-09-10T17:50:00Z',
  },
  {
    id: 'task_005',
    key: 'PUL-92',
    title: 'Add glassmorphism and bento-card presets to Tailwind config',
    description: 'Define standardized backdrop-filter tokens, subtle border glows, and responsive grid layouts.',
    status: 'done',
    priority: 'medium',
    projectId: 'proj_pulse_design',
    projectName: 'Pulse Design System v3',
    assignee: MOCK_PROJECTS[2].members[0],
    dueDate: '2026-09-11T15:00:00Z',
    estimatedHours: 4,
    loggedHours: 4,
    tags: ['Tailwind', 'UI/UX'],
    commentsCount: 1,
    createdAt: '2026-09-09T09:00:00Z',
    updatedAt: '2026-09-11T14:40:00Z',
  },
  {
    id: 'task_006',
    key: 'APX-12',
    title: 'Compile Rust SHA-256 token verification routine to WebAssembly',
    description: 'Ensure memory footprint is under 64KB for edge deployment on Cloudflare Workers.',
    status: 'in_progress',
    priority: 'urgent',
    projectId: 'proj_apex_edge',
    projectName: 'Apex Edge Cache API Gateway',
    assignee: MOCK_PROJECTS[3].members[0],
    dueDate: '2026-09-16T18:00:00Z',
    estimatedHours: 14,
    loggedHours: 10,
    tags: ['Rust', 'Wasm', 'Security'],
    commentsCount: 6,
    createdAt: '2026-09-04T10:00:00Z',
    updatedAt: '2026-09-11T15:10:00Z',
  },
  {
    id: 'task_007',
    key: 'NEX-112',
    title: 'Automate canary rollback pipeline on Prometheus error budget burn',
    description: 'Integrate Argo Rollouts with Prometheus alerting rules for instant self-healing deploys.',
    status: 'in_progress',
    priority: 'medium',
    projectId: 'proj_cloud_nexus',
    projectName: 'Nexus Cloud Control Plane',
    assignee: MOCK_PROJECTS[0].members[2],
    dueDate: '2026-09-22T18:00:00Z',
    estimatedHours: 10,
    loggedHours: 4,
    tags: ['DevOps', 'Kubernetes', 'CI/CD'],
    commentsCount: 4,
    createdAt: '2026-09-06T14:00:00Z',
    updatedAt: '2026-09-10T16:00:00Z',
  },
  {
    id: 'task_008',
    key: 'SYN-50',
    title: 'Implement differential privacy Laplace noise perturbation layer',
    description: 'Verify epsilon-delta privacy budget guarantees with empirical membership inference attacks.',
    status: 'todo',
    priority: 'low',
    projectId: 'proj_synth_ai',
    projectName: 'Synthetic Data & ML Pipeline',
    assignee: MOCK_PROJECTS[1].members[1],
    dueDate: '2026-09-29T18:00:00Z',
    estimatedHours: 20,
    loggedHours: 0,
    tags: ['Privacy', 'Math', 'Python'],
    commentsCount: 0,
    createdAt: '2026-09-09T17:00:00Z',
    updatedAt: '2026-09-09T17:00:00Z',
  },
  {
    id: 'task_009',
    key: 'APX-18',
    title: 'Design distributed rate-limiter with Redis sliding window logs',
    description: 'Support 500,000 req/sec sustained burst with sub-millisecond atomic eval scripts.',
    status: 'todo',
    priority: 'high',
    projectId: 'proj_apex_edge',
    projectName: 'Apex Edge Cache API Gateway',
    assignee: MOCK_PROJECTS[3].members[1],
    dueDate: '2026-09-20T18:00:00Z',
    estimatedHours: 8,
    loggedHours: 0,
    tags: ['Redis', 'Architecture', 'HighScale'],
    commentsCount: 3,
    createdAt: '2026-09-10T10:00:00Z',
    updatedAt: '2026-09-10T10:00:00Z',
  },
  {
    id: 'task_010',
    key: 'PUL-95',
    title: 'Create interactive 3D hero showcase for documentation portal',
    description: 'Showcase dynamic physics and materials reacting to cursor gestures in the documentation header.',
    status: 'in_review',
    priority: 'low',
    projectId: 'proj_pulse_design',
    projectName: 'Pulse Design System v3',
    assignee: MOCK_PROJECTS[2].members[0],
    dueDate: '2026-09-17T18:00:00Z',
    estimatedHours: 6,
    loggedHours: 5.5,
    tags: ['3D', 'Documentation', 'Showcase'],
    commentsCount: 2,
    createdAt: '2026-09-07T11:00:00Z',
    updatedAt: '2026-09-11T13:00:00Z',
  },
];

export const MOCK_ACTIVITIES: ActivityItem[] = [
  {
    id: 'act_01',
    type: 'pull_request',
    title: 'Merged PR #342: feat(mesh): Add 3D procedural shader hero with mouse parallax',
    description: 'Merged into main branch with 100% test coverage and reduced motion checks.',
    timestamp: '12 minutes ago',
    repoName: 'acme/pulse-ui-tokens',
    branch: 'main',
    author: {
      name: 'Alex Vance',
      avatarUrl: MOCK_USER.avatarUrl,
    },
  },
  {
    id: 'act_02',
    type: 'commit',
    title: 'commit e7b39a: optimize R3F Canvas geometry caching & disable SSR hydration',
    description: 'Reduced initial client payload and improved first contentful paint by 240ms.',
    timestamp: '1 hour ago',
    repoName: 'acme/nexus-control-plane',
    author: {
      name: 'Alex Vance',
      avatarUrl: MOCK_USER.avatarUrl,
    },
  },
  {
    id: 'act_03',
    type: 'deployment',
    title: 'Deployed v2.8.0 to Production (us-east, eu-west, ap-southeast)',
    description: 'Deployment verified healthy with 0 error rate over 15-minute soak window.',
    timestamp: '3 hours ago',
    repoName: 'acme/apex-edge-gateway',
    author: {
      name: 'Elena Rostova',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    },
  },
  {
    id: 'act_04',
    type: 'review',
    title: 'Approved PR #89: refactor(api): abstract mock layer for future REST endpoints',
    description: 'Code looks clean and forward-compatible for Task 2 backend wiring.',
    timestamp: '5 hours ago',
    repoName: 'acme/synthetic-data-engine',
    author: {
      name: 'Marcus Chen',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    },
  },
  {
    id: 'act_05',
    type: 'task_completed',
    title: 'Completed task PUL-92: Bento-grid preset tokens and glass styles',
    description: 'Completed 2 hours ahead of sprint estimation.',
    timestamp: 'Yesterday at 4:40 PM',
    repoName: 'acme/pulse-ui-tokens',
    author: {
      name: 'Alex Vance',
      avatarUrl: MOCK_USER.avatarUrl,
    },
  },
];

export const MOCK_PRODUCTIVITY_SUMMARY: ProductivitySummary = {
  weeklyVelocity: [
    { day: 'Mon', hours: 7.2, commits: 8, tasks: 3 },
    { day: 'Tue', hours: 8.5, commits: 12, tasks: 4 },
    { day: 'Wed', hours: 6.8, commits: 7, tasks: 2 },
    { day: 'Thu', hours: 9.1, commits: 14, tasks: 5 },
    { day: 'Fri', hours: 8.0, commits: 9, tasks: 4 },
    { day: 'Sat', hours: 2.5, commits: 3, tasks: 1 },
    { day: 'Sun', hours: 1.0, commits: 1, tasks: 0 },
  ],
  projectCompletionRates: [
    { name: 'Pulse UI System', key: 'PUL', rate: 92, color: '#10b981' },
    { name: 'Nexus Control', key: 'NEX', rate: 76, color: '#6366f1' },
    { name: 'Synthetic AI', key: 'SYN', rate: 54, color: '#a855f7' },
    { name: 'Apex Gateway', key: 'APX', rate: 35, color: '#f59e0b' },
  ],
  focusScore: 94,
  streakCount: 14,
  openPullRequestsCount: 5,
};
